[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build && npx prisma generate"

[deploy]
startCommand = "npx prisma migrate deploy && npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_VERSION = "20.19.0"

