services:
  # PostgreSQL Database
  - type: pserv
    name: newtumblr-db
    env: docker
    plan: free
    ipAllowList: []

  # Backend API
  - type: web
    name: newtumblr-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: newtumblr-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
    healthCheckPath: /api/health

  # Frontend
  - type: web
    name: newtumblr-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://newtumblr-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

